pull_request_rules:
  - name: Alert on dependency updates
    conditions:
      - files~=package.json
    actions:
      label:
        add:
          - dependency update
      comment:
        message: >-
          This PR introduces updates to crucial dependencies. Please review and
          test.
      assign:
        users:
          - iamshubhankarkhare
  - name: Auto-rebase on conflict
    conditions:
      - conflict
      - base=master
    actions:
      rebase: null
      comment:
        message: This PR has been automatically rebased due to a conflict.
queue_rules:
  - name: my_queue
    conditions:
      - base=master
