queue_rules:
  - name: test
    merge_conditions:
      - "#approved-reviews-by>=1"
pull_request_rules:
  - name: Alert on dependency updates
    conditions:
      - files~=package.json
    actions:
      label:
        add:
          - dependency update
      comment:
        message: >-
          This PR introduces updates to crucial dependencies. Please review and
          test.
      assign:
        users:
          - iamshubhankarkhare
      queue:
        
