pull_request_rules:
  - name: Alert on dependency updates
    conditions:
      - files~=package.json
    actions:
      label:
        add:
          - dependency update
      comment:
        message: >-
          This PR introduces updates to crucial dependencies. Please review and
          test.
      assign:
        users:
          - iamshubhankarkhare
  - name: Auto-rebase
    conditions:
      - files~=package.json
      - base=master
    actions:
      rebase: null
      comment:
        message: This PR has been automatically rebased.
  - name: Add in merge queue
    conditions:
      - files~=package.json
      - base=master
    actions:
      queue:
        name: my_queue
queue_rules:
  - name: my_queue
    conditions:
      - base=master
