queue_rules:
  - name: hotfix
    routing_conditions:
      - label=hotfix
    merge_conditions:
      - label=hotfix

  - name: default
    merge_conditions:
      - label!=hotfix

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
    actions:
      queue:
